version: '3'
services:
   web: 
    networks:
      - web
    container_name: frontend
    build:
      context: .       
    volumes:
      - ./target/LoginWebApp-1.war:/usr/local/tomcat/webapps/LoginWebApp-1.war
    ports:
      - '8085:8080'
volumes:
    db_vol:  
      external: False

networks:
 web:
    external: false
    
